// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcfutbncphzgvvcrwiqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjZnV0Ym5jcGh6Z3Z2Y3J3aXF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MTcyNTgsImV4cCI6MjA2NzE5MzI1OH0.cRC1nkR89hU72R4Tv1up1-cWbO1vjUfLPIIl18Mgcls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});